### ISSUE TITLE
rename repo to pylonsprojectorg

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#1]
Names are important. "pylonsprojectorg" is explicit. "ppo" means "Preferred Provider Organization" to me, or nothing. Brevity is bad in this case, especially because it took me a long time to figure out how pylonshq, pylonsrtd, and each project's documentation were intertwined. [I still can't get it right!](https://github.com/Pylons/pylonsrtd/issues/44#issuecomment-135599956) :stuck_out_tongue_winking_eye:

**Comment by stevepiercy** [comment]
@blaflamme Pretty please?

**Comment by mmerickel** [comment]
Repos can have dots in them. I'd just name one pylonsproject.org and one
trypyramid.com.

**Comment by stevepiercy** [comment]
> Repos can have dots in them.

Even better! TIL.

I do not have sufficient privileges to manage repos under Pylons.

**Comment by blaflamme** [comment]
I still prefer short names than super long names and for website projects I tend to avoid at all costs the use of domain names. Under each repos we also have a description that tells people what's the purpose of the project, so I doubt we'll have any confusion here and we'll probably be the only ones who'll use the repo :P

**Comment by stevepiercy** [comment]
I understand we're you're coming from, but in this case I disagree. Let's use explicit names for the following reasons.

* When the repo name and URL align, that helps support SEO, marketing, and branding.
* I had a difficult time sorting out pylonshq, pylonsrtd, and so on. That hurt in many ways.
* Let's make it easy to figure out the project's purpose by its name and URL only. That's good marketing and branding. Why must I look at a description, too?
* Many other people are interested in contributing to this marketing project and "tpc", too.
* In this case, this project is a website with the domain name pylonsproject.org, so it makes sense to align the repo name and the domain name.
* The current name 'ppo' represents 'pylonsproject.org' anyway. Why make it obscure or abstract?
* Examples that follow this convention include https://github.com/gratipay/gratipay.com and https://github.com/rtfd/readthedocs.org

I am BEGGING. I want this really, really badly.

**Comment by stevepiercy** [comment]
Actually www.pylonsproject.org would be even better than plain old pylonsproject.org, and would disambiguate it from docs.pylonsproject.org. Let's do that.
