### ISSUE TITLE
Include space for sponsors

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#10]
JetBrains gives FOSS licenses to the core contributors of Pylons Project projects. We should acknowledge their support of FOSS.

See https://github.com/Pylons/trypyramid.com/issues/194

**Comment by stevepiercy** [comment]
Here is some content:
http://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/development_tools/pycharm.html#install-pycharm

And a logo:
https://www.jetbrains.com/company/press/?fromMenu

**Comment by ikolar** [comment]
Hey, would either of [these two](http://imgur.com/a/B6R2x) work? The firrst has a jetbrains logo on the main page, the second mentions PyCharm in the "How to participate" sub page.

**Comment by stevepiercy** [comment]
Hi @ikolar, we discussed in [IRC](https://botbot.me/freenode/pyramid/2017-01-17/?msg=79472065&page=1). We don't know yet how we want to implement recognition of sponsors, contributors, and others. We need to think about it some more, which may include new pages.

**Comment by ikolar** [comment]
Ok, thanks.

**Comment by stevepiercy** [comment]
I think the best option is a new page. Then we don't have to contend with a page's existing layout, and gives us a fairly blank canvas to work on. I also like a separate URL that we can give out to sponsors, both current and potential.

@blaflamme do you have any feedback before I take this one on?

We have Rackspace and JetBrains as sponsors. Any others?

**Comment by blaflamme** [comment]
Linode for the hosting

**Comment by stevepiercy** [comment]
For the new page, Sponsors, I think it should go under Community navigation item.

**Comment by stevepiercy** [comment]
@blaflamme I lack the information to complete a request for a Powered by Rackspace logo. Can you please fill out the form, and forward the artwork to me?
https://www.rackspace.com/forms/logorequest

Also what do each of Linode and Rackspace provide to us?

**Comment by stevepiercy** [comment]
@blaflamme also if you have referral links where our account can receive credits, then I'd like to use them on this page.

**Comment by blaflamme** [comment]
@stevepiercy ATM only webob is still powered by Rackspace if I recall and I'll move it over Linode as soon as I have a bit of time. Then nothing will remain on Rackspace, and it's a bit odd since each year they never remember the OSS free thingy and I got billed and then they have to figure out, and so on... I suspect it will end sooner than later without any notice, so probably wiser to just drop them off.

**Comment by stevepiercy** [comment]
Who pays for the Rackspace hosted email?

Who pays for the DNS, domain name registration?

Whoever pays for these services is a sponsor, whether they want to admit it. :wink:

Are there any other services, products, or contributions we receive?

**Comment by blaflamme** [comment]
I pay for domain names and hosted emails, DNS is provided by Linode.

**Comment by stevepiercy** [comment]
Would you like to receive acknowledgment for your financial contribution, or remain silent?

**Comment by blaflamme** [comment]
no need... we're a lot in this project who are giving money or time, the important part is having this project rocking!

**Comment by stevepiercy** [comment]
OK. I'm closing this issue as completed.
