### ISSUE TITLE
Accessibility of links

### ISSUE THREAD

**Issue by zupo** [Pylons/pylonsproject.org#19]
@livike suggested we should do something else to the styling of links in the content area. And I agree completely. Having them painted blue makes them indistinguishable from normal text for people with visual impairments. We need to either bold them, underline them or something else.

**Comment by blaflamme** [comment]
yes this is something I'll work on

**Comment by blaflamme** [comment]
Links are now in lighter blue, so impaired people can see it as a shade of grey or other color, and they have underline on hover.

**Comment by stevepiercy** [comment]
The links are much more distinguishable now. Closing.
