### ISSUE TITLE
Project navigation links are disorienting

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#29]
- [x] Remove Projects submenu, and make link go to /projects.html.
- [x] ~I was disoriented when I clicked on links under Projects, and was taken to another site altogether. I expect a warning or indicator that I'm going to a different website when a link is in the navigation. I understand that we originally wanted a full page for each project on pylonsproject.org, but we just don't have enough content to justify that and I like the current layout.~
- [x] Under Projects, "more..." is a vague label for the link. I prefer "Our projects" which also aligns with the page heading.
- [x] Change `<title>` for /projects.html from "Projects" to "Our Projects" as well.

**Comment by blaflamme** [comment]
What I propose is to have no submenu under projects and go directly to the projects page, or if we keep the submenu we can add an icon to the right to show it's an external link. But we already have the main projects on the home page, a pyramid featured section, and the projects page, I don't see the need to have them displayed in the submenu.

**Comment by stevepiercy** [comment]
I prefer removal of the submenu, too. Updated checklist.

**Comment by blaflamme** [comment]
@stevepiercy will work on this too... btw point #3 will be resolved when #1 is done.

**Comment by blaflamme** [comment]
Done
