### ISSUE TITLE
add HTTPS

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#30]
Let's Encrypt, y'all!

**Comment by blaflamme** [comment]
I'll do it

**Comment by stevepiercy** [comment]
@blaflamme can you take care of this one, or is it something I can do?

**Comment by blaflamme** [comment]
@stevepiercy yes I can

**Comment by stevepiercy** [comment]
https://pylonsproject.org currently loads the content of https://trypyramid.com/ This is bad.

**Comment by bertjwregeer** [comment]
SNI is not configured correctly.

**Comment by blaflamme** [comment]
I'll take a look later today, cert is not activated on the domain and if I recall all https will probably route to the main domain by default.

**Comment by stevepiercy** [comment]
@blaflamme Our GSoC student noticed that we still don't have HTTPS enabled. Please let me know if this is something that I can do.

**Comment by stevepiercy** [comment]
@mmerickel noted that [sites that are served over HTTPS that use `pylons-sphinx-themes` are not loading that theme's stylesheets](https://pyramid.readthedocs.io/en/latest/). This is [due to](https://github.com/Pylons/pylons-sphinx-themes/blob/master/pylons_sphinx_themes/pylons/layout.html#L4-L5):

```html
<link rel="stylesheet" href="http://static.pylonsproject.org/fonts/nobile/stylesheet.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="http://static.pylonsproject.org/fonts/neuton/stylesheet.css" type="text/css" media="screen" charset="utf-8" />
```

I must change the `href` attribute either to another domain name entirely (suboptimal) or if this issue ever gets resolved then I can use "https" (preferable).

**Comment by stevepiercy** [comment]
@bbangert are you the admin for `static.pylonsproject.org`?

**Comment by blaflamme** [comment]
@stevepiercy https is installed on pylonsproject.org

**Comment by stevepiercy** [comment]
I've updated links on the major projects:
* pyramid and its three cookiecutters across all branches
* webob
* deform
* pyramid_debugtoolbar

Marketing Sites:
* pylonsrtd
* trypyramid.com
* pylonsproject.org
* webob.org
* pyramid_cookbook (no changes)
* pyramid_tutorials
