### ISSUE TITLE
Link to the pylons-discuss ML is broken

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pylonsproject.org#35]
As posted on IRC:

```
10:17:24 < mengu> hi all.
10:18:30 < mengu> the link to pylons-discuss ml is broken at http://pylonsproject.org/community-support.html
```

**Comment by stevepiercy** [comment]
This was fixed in 401df92819b56585a90d258606a43df3f7db1f8b but not deployed to production.

**Comment by stevepiercy** [comment]
@blaflamme I can't push to production. My public key does not work for the remote repo:

```bash
stevepi-mbp:pylonsproject.org stevepiercy$ git remote add production ssh://pylons@marketing.pylonsproject.org/home/pylons/repos/pylonsproject.org.git
stevepi-mbp:pylonsproject.org stevepiercy$ git push production master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I was able to ``git push --tags``, but that's as far as I could go.

**Comment by blaflamme** [comment]
@stevepiercy weird thing, the user/access is the same for both trypyramid.com and pylonsproject.org repos. Can you try both again and get back to me?

**Comment by stevepiercy** [comment]
@blaflamme still not working. I'm traveling using my previous MBP. That might have something to do with it. Should I resend you my public key?

**Comment by stevepiercy** [comment]
I figured it out. I needed to configure ssh to use a specific local private key.

Closing as this is now pushed to production.

**Comment by blaflamme** [comment]
@stevepiercy great! I'm glad you figured it out :)
