### ISSUE TITLE
Set up email aliases and accounts *@pylonsproject.org

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#4]
We need to have email addresses registered for every service we use under the Pylons Project. Please add services, addresses, and recipients (omit actual email addresses from the list, using instead GitHub handles).

| Twitter | Email Alias/Account | Recipients |
| --- | --- | --- |
| @PylonsProject (renamed from @Pylons) | PylonsProject@ PylonsProject.twitter@ | Pylons Project marketing group (@stevepiercy, @goodwill, pylons@pylonsproject.org) |
| @TryPyramid (archive) | trypyramid.twitter@ | pylons@pylonsproject.org |
| @Pylons (squatting) | pylons.twitter@ | pylons@pylonsproject.org |
| ~~-~~ | ~~pylonsweb@~~ | ~~Pylons web framework marketing group (TBD, pylons@pylonsproject.org)~~ No longer needed |
| - | webob@ | WebOb marketing group (@bertjwregeer, pylons@pylonsproject.org) |
| - | pylons@ | Full email account as a backup to all communications |

**Comment by stevepiercy** [comment]
Should we rename @pylons to @pylonsweb in order to avoid ambiguity?

**Comment by blaflamme** [comment]
Since the base account is pylons@pylonsproject.org it would be better pylonsweb

**Comment by stevepiercy** [comment]
What is the email address pylons@pylonsproject.org used for?

**Comment by blaflamme** [comment]
It's just the internal real address where it gets everything so at the same time we'll have a backup of all communications accessible via the webmail.

**Comment by blaflamme** [comment]
@stevepiercy there is just one email account (pylons@pylonsproject.org), we don't need more since we can create aliases and dispatch to our own email accounts. At the same time all messages go through this account, so anyone could have access to all messages sent to aliases if there's a need for.

**Comment by stevepiercy** [comment]
@blaflamme are you saying that every alias forwards a copy of each message that it receives to pylons@pylonsproject.org as well as the other specified recipients above? If so, we should document that, too.

**Comment by blaflamme** [comment]
@stevepiercy yes it does

**Comment by stevepiercy** [comment]
@goodwillcoding please hit me up in IRC to take care of changing the Twitter handle for pylons to pylonsproject.

**Comment by stevepiercy** [comment]
@blaflamme I also changed the table at the top. I've found that it's a lot of work to maintain active Twitter accounts, and there is a lot of duplication of posts, so I removed Twitter handles that were proposed at one time.

`@Pylons` should be renamed ``@PylonsProject`, because that is what it has evolved into as far as content, and no one really follows @Pylons for the Pylons web framework.

**Comment by stevepiercy** [comment]
After a [discussion with @mmerickel, @goodwillcoding, and others on IRC a couple of weeks ago](https://botbot.me/freenode/pyramid/2017-02-24/?msg=81517507&page=3), I'm considering a discontinuation of the twitter handle `@TryPyramid`, and telling users to follow `@PylonsProject` instead, after changing `@Pylons` to `@PylonsProject`. Here's why:

* There is a significant majority overlap in both users and content. Roughly 2/3 of `@TryPyramid` followers also follow `@Pylons`. I guess 90% of the content is duplicated or retweets of each account.
* I am the only person tweeting on behalf of either account, and dealing with two accounts is not worth the extra maintenance burden.

We would still hold onto all three twitter handles—`@TryPyramid`, `@PylonsProject`, and `@Pylons`—but inform users to follow the primary renamed handle `@PylonsProject`.

Ping @blaflamme, too, for comment.

refs: https://github.com/Pylons/trypyramid.com/issues/39 and https://github.com/Pylons/trypyramid.com/issues/8

**Comment by stevepiercy** [comment]
@blaflamme I currently use email aliases that point to my personal domain `stevepiercy.com` for `@TryPyramid` and `@Pylons`, and they should have aliases under the domain `pylonsproject.org`.

Additionally I have reduced the Twitter handles down to 1 active (`@PylonsProject`) and two archival (`@TryPyramid` and `@Pylons`). Twitter requires a unique email address per account, unfortunately. For consistency, let's use:

* `pylonsproject.twitter@pylonsproject.org`
* `pylons.twitter@pylonsproject.org`
* `trypyramid.twitter@pylonsproject.org`

Please let me know when they are set up, so I can update these two Twitter handles. Also feel free to remove unused email aliases and folders, including the following:

* pylonsweb
* pyramid
* trypyramid
* webob

**Comment by blaflamme** [comment]
@stevepiercy done, I'll keep others for some time.

**Comment by stevepiercy** [comment]
Thank you! I'll close this issue.

refs: https://github.com/Pylons/hosted-services/
