### ISSUE TITLE
Twitter widgets

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#42]
We used to have a Twitter widget on the home page, but there were problems with rate limiting and caching when we used the API. We could use the web widgets instead. I don't know where would be a good spot, perhaps at the end of the home page? On a new separate page?

[Twitter Timeline](https://dev.twitter.com/web/embedded-timelines)
```html
<a href="https://twitter.com/PylonsProject"
    class="twitter-timeline">Tweets by PylonsProject</a>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

[Twitter Follow Button](https://dev.twitter.com/web/follow-button)
```html
<a href="https://twitter.com/PylonsProject"
    class="twitter-follow-button"
    data-size="large"
    data-lang="en"
    data-dnt="true"
    data-show-count="true">Follow @PylonsProject</a>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by stevepiercy** [comment]
@blaflamme do you have any preference as to whether:

1. we use Twitter API versus a widget?
2. its placement?

I really want to push Twitter as a communication channel.

**Comment by blaflamme** [comment]
@stevepiercy a widget will be easier to add, lets see where it can go. The format will hardly fits the main page OTOH.

**Comment by stevepiercy** [comment]
@blaflamme I think a new page is needed, Contact. It can include widgets for Twitter, IRC, and the Google Group. I am debating whether it should go under Community or About. I'm leaning toward About.

Also what do you think about having a Twitter follow button in the footer sitewide?

IRC

```html
<iframe src="http://webchat.freenode.net?channels=%23pyramid&uio=d4" width="647" height="400"></iframe>
```

Google Group snippet

```html
<iframe id="forum_embed"
  src="javascript:void(0)"
  scrolling="no"
  frameborder="0"
  width="900"
  height="700">
</iframe>
<script type="text/javascript">
  document.getElementById('forum_embed').src =
     'https://groups.google.com/forum/embed/?place=forum/pylons-discuss'
     + '&showsearch=true&showpopout=true&showtabs=false'
     + '&parenturl=' + encodeURIComponent(window.location.href);
</script>
```

**Comment by blaflamme** [comment]
@stevepiercy it all make sense

**Comment by stevepiercy** [comment]
@blaflamme have a look. The Contact page is not that great looking, but I think it works.

**Comment by stevepiercy** [comment]
This is done: http://pylonsproject.org/about-contact.html
