### ISSUE TITLE
Content duplicated on Home and About Pylons Project

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#43]
The content at the bottom of the [home page](http://pylonsproject.org/) and on [About Pylons Project](http://pylonsproject.org/about-pylons-project.html) are duplicitous.

We should replace the content on the bottom of the home page with something unique.

**Comment by blaflamme** [comment]
I think we should have something more elaborated on the about page and keep the summary on the home page. I think there is far more to say.

**Comment by stevepiercy** [comment]
OK, I'm also reviewing content from the [pylonsrtd repo](https://github.com/Pylons/pylonsrtd/issues/65) to see what should be moved over.  There's probably something good in there.

**Comment by stevepiercy** [comment]
Closed by #49
