### ISSUE TITLE
Set up static.pylonsproject.org and webob.org on marketing with HTTPS

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#55]
I would like access to take all the necessary steps to enable HTTPS for static.pylonsproject.org and webob.org on the Linode box that hosts marketing.pylonsproject.org.

Any documentation that uses pylons-sphinx-themes and is served over HTTPS cannot load the stylesheets or fonts. See https://github.com/Pylons/pylonsproject.org/issues/30#issuecomment-308331719 

I have access to the old pylonshq server at Rackspace, including static.pylonsproject.org and webob.org, and can copy its content anywhere.

**Comment by blaflamme** [comment]
@stevepiercy can you make the assets available to, like via dropbox, so I can have a copy to install on the server. I'll also have to move webob.org to the box since it's not hosted there, and then I'll be able to add both certs to them.

**Comment by blaflamme** [comment]
@stevepiercy ok I moved static.pylonsproject.org and webob.org to marketing.pylonsproject.org, setuped nginx to serve them and updated DNS entries. Once they'll be served by the right IP, later today, I'll setup SSL with letsencrypt. So we should have all of them using SSL and static served HTTP+S

**Comment by stevepiercy** [comment]
Thanks @blaflamme.

One more request: redirect HTTP to HTTPS for all sites.

I've got a new release for pylons-sphinx-themes ready to go when you have completed this.

**Comment by blaflamme** [comment]
@stevepiercy 

ok webob.org is active and redirects all to HTTPS, static.pylonsproject.org can serve both.

**Comment by stevepiercy** [comment]
Thanks @blaflamme !
