### ISSUE TITLE
HTTPS for docs.pylonsproject.org

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pylonsproject.org#56]
It's possible to setup HTTPS for our project (and subproject) documentation if we configure our host properly.

1. Configure a VHOST on our server that can proxy requests from docs.pylonsproject.org to pylons.readthedocs.org by following this nginx configuration guide: https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl

2. Set the `X-RTD-SLUG` proxy header to `pylons`. This is the correct setting and will work even for our subproject docs. See https://pylons.readthedocs.io/projects/pyramid/en/latest/ as an example of how the path part of the url matches our current paths.

2. Configure HTTPS on that VHOST.

3. Point docs.pylonsproject.org at our server.

4. Optionally redirect HTTP to HTTPS (yes please).

5. Optionally configure nginx to cache some of the docs assets.

**Comment by stevepiercy** [comment]
> proxy requests from docs.pylonsproject.org to pylons.readthedocs.org

Did you mean "proxy requests from docs.pylonsproject.org to pylons.readthedocs._io_"?

**Comment by mmerickel** [comment]
Yes

**Comment by stevepiercy** [comment]
@blaflamme it looks like you don't use [certbot](https://certbot.eff.org/#ubuntuxenial-nginx), but some kind of manual process instead. Can you verify or correct what I've dug up?

- add entry to `/etc/hosts` for hostname
- add `/etc/nginx/sites-available/<hostname>.conf`
- symlink `ln -s /etc/nginx/sites-available/<hostname>.conf /etc/nginx/sites-enabled/<hostname>.conf`
- edit `/etc/letsencrypt/cli.ini`, adding hostname
- add `/etc/letsencrypt/renewal/<hostname>.conf`
- add crontab entry `crontab -e`

**Comment by blaflamme** [comment]
it was done before letsencrypt becomes certbot, so the command is /opt/letsencrypt/letsencrypt-auto

feel free to update the process to use latest certbot. at the moment it uses /usr/local/bin/le-renewal, and look at root user crontab, not global one.

**Comment by stevepiercy** [comment]
I'll work on this either Sun or Mon night.

**Comment by stevepiercy** [comment]
I think I got steps 1-5 above set up correctly, but I'm not altogether sure. My browsers return inconsistent results. Chrome seems to be working by redirecting http to https and getting the certificate for `docs.pylonsproject.org`, but Firefox, Safari, and Opera do not redirect http to https and try to get a certificate from `*.readthedocs.io`. Maybe it's my router.

I found a minor issue in Chrome which displays an error "Active content with certificate errors", which is "solved" by restarting your browser.

Once the dust settles and a few more people who don't have my jacked results can verify that things are working for them, I'll add caching in step 6.

**Comment by stevepiercy** [comment]
Switching my iMac's and router's DNS servers away from my ISP's to OpenDNS's resolved the weirdness. Ugh. Still I'd like a few more eyeballs to verify I didn't make a mistake.

**Comment by stevepiercy** [comment]
I also configured cron to use `/usr/bin/certbot renew` instead of `le-renewal`.

I've enabled caching for `docs.pylonsproject.org` following https://www.nginx.com/blog/nginx-caching-guide/.

If someone would like to verify the configuration, I'd be happy to grant them access.

**Comment by bertjwregeer** [comment]
Seems to be working without issues.
