### ISSUE TITLE
Access to fonts on static.pylonsproject.org blocked by CORS

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#59]
When visiting https://pyramid.readthedocs.io/en/latest/, the font files are blocked from loading by CORS.

Please add a `Access-Control-Allow-Origin` header for `*` [[edited per @mmerickel comment](https://github.com/Pylons/pylonsproject.org/issues/59#issuecomment-309169566)]. See this [serverfault post](https://serverfault.com/q/162429) for further information.

```
Access to Font at 'https://static.pylonsproject.org/fonts/nobile/nobile-webfont.woff' from origin 'https://pyramid.readthedocs.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://pyramid.readthedocs.io' is therefore not allowed access.
(index):1 Access to Font at 'https://static.pylonsproject.org/fonts/neuton/Neuton-webfont.woff' from origin 'https://pyramid.readthedocs.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://pyramid.readthedocs.io' is therefore not allowed access.
(index):1 GET https://static.pylonsproject.org/fonts/neuton/Neuton-webfont.ttf net::ERR_CONNECTION_REFUSED
(index):1 Access to Font at 'https://static.pylonsproject.org/fonts/nobile/nobile-webfont.ttf' from origin 'https://pyramid.readthedocs.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://pyramid.readthedocs.io' is therefore not allowed access.
```

**Comment by mmerickel** [comment]
Great timing, I was literally visiting the github repo to mention this issue when your email popped up.

**Comment by mmerickel** [comment]
This header needs to support `*` not just readthedocs.io unless that's the only place the pylons-sphinx-themes package is allowed to be used. (Hint michael.merickel.org/projects/pyramid_auth_demo is broken right now)

**Comment by stevepiercy** [comment]
I also [cut another release](https://pypi.python.org/pypi/pylons-sphinx-themes/1.0.2) that removes the protocol, and I'm rebuilding the docs again.

**Comment by stevepiercy** [comment]
@blaflamme took care of this. https://pyramid.readthedocs.io/en/latest/
