### ISSUE TITLE
nginx will not launch on server reboot

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#60]
A manual start of nginx works. But nginx will not launch on server reboot. The server is now running Ubuntu 16.04 LTS.

In `/var/log/nginx/error.log`:

```
2017/06/17 03:25:00 [emerg] 3577#3577: bind() to [2600:3c03::f03c:91ff:fef1:a15b]:443 failed (99: Cannot assign requested address)
```

That's the correct IPv6. I don't know whether nginx ever launched on server reboot. @blaflamme do you know?

I've been Googling for over an hour trying various things, but none work.

**Comment by blaflamme** [comment]
it looks like nginx was not enabled in systemd, you did an upgrade to ubuntu 16.04? I enabled it so lets see if it starts when you reboot.

**Comment by blaflamme** [comment]
it looks like when nginx starts up the ipv6 is not available, like if after=network.target is not enough in the systemd service file. I just removed nginx serving out ipv6 for now until the problem is resolved.

**Comment by stevepiercy** [comment]
For the record, before the upgrade to 16.04, when I did a reboot on 14.04 nginx did not start on reboot, showing the same issue of not binding to IPv6.

I'll try again tonight. Any suggestions appreciated on how to get nginx to launch after reboot with IPv6 configured.

**Comment by blaflamme** [comment]
it now starts up after a reboot, ipv6 needs fixing... could be how eth0 ipv6 is configured, the systemd nginx service file looks ok.

**Comment by stevepiercy** [comment]
Perhaps [this answer](https://serverfault.com/a/392926), but for IPv6 instead of IPv4?

Another option is to bind to any address with `listen [::]:443 ssl`.

If you don't get a chance to poke at it today, I'll look at it tonight.

**Comment by blaflamme** [comment]
But it works for IPv4... I know that Linode provides an auto-network configuration, so I'm asking them about the nginx issue to see if there's something to do with how it works or if we need to go with manual config.

**Comment by stevepiercy** [comment]
Let me know what Linode says and what you learn.

**Comment by blaflamme** [comment]
ok fixed... I disabled the auto-network configuration and manually configured eth0 for IPv6, now nginx starts at system reboot.

**Comment by stevepiercy** [comment]
For our future selves, note changes in `/etc/network/interfaces` as mentioned in this [Linode KB article](https://www.linode.com/docs/networking/linux-static-ip-configuration#ubuntu).

[Another possible option I found](https://serverfault.com/a/421466), but could not get to work:

```
post-up while ip -6 addr show tentative | grep . > /dev/null ; do sleep 1 ; done
```

Doing a `sleep` during network interfaces startup might have some unintended consequences.

The helpful comments at the top of the current `/etc/network/interfaces` file did not previously exist in `/etc/network/.interfaces.linode-orig`:

```
# Generated by Linode Network Helper
# Sat Jun 17 14:50:59 2017 UTC
#
# This file is automatically generated on each boot with your Linode's
# current network configuration. If you need to modify this file, please
# first disable the 'Auto-configure Networking' setting within your Linode's
# configuration profile:
#  - https://manager.linode.com/linodes/config/Marketing?id=2358621
#
# For more information on Network Helper:
#  - https://www.linode.com/docs/platform/network-helper
```

:confounded:
