### ISSUE TITLE
Site Map v1.0

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsproject.org#7]
This issue describes the proposed organization of the website for its 1.0 launch.

Please discuss and add your comments.
# Primary Navigation
- [x] Home
- [x] Projects
- [x] Community
- [x] About
# Secondary Navigation
## Projects
- [x] Pyramid
- [x] WebOb
- [x] SubstanceD
## Community
- [x] [Participate](http://www.pylonsproject.org/community/how-to-participate)
- [x] [Contribute](http://www.pylonsproject.org/community/how-to-contribute)
- [x] Code of Conduct
- [x] Support
## About
- [x] Pylons Project
- [x] Pylons Framework (deprecated)
- [x] History
- [x] License

**Comment by JanLikar** [comment]
I'm working on "about".

**Comment by zupo** [comment]
I'm continuing with "Contribute".

**Comment by zupo** [comment]
Onward to "Code of Conduct".

**Comment by zupo** [comment]
Which projects should be under Projects? All currently listed on index of upcoming.pylonsproject.org?

**Comment by stevepiercy** [comment]
You can get a list of all Pylons projects by either:
* https://api.github.com/orgs/Pylons/repos
* https://github.com/Pylons

One could use the GitHub API to get the data, and cache results to avoid API rate limiting.

I think we don't want to exclude any repos now, unless it's clearly not appropriate to include, such as a few throwaway or aborted Pylons repos.

Curation of the repos might include:
* provide its status (active, maintenance-only/no bug fixes, not maintained)
* to suggest a replacement if any
* whether it needs a maintainer

**Comment by zupo** [comment]
1.) Why do we need rate limiting? The API is queried only at build time, which only happens once every few days/weeks.

2.) I don't understand what you mean with "curation".

**Comment by zupo** [comment]
What is next? What else needs to be done?

**Comment by stevepiercy** [comment]
1. For example, to get stats, or recent PRs or issues. Some things, like the repo list, rarely change, so build time is fine for that.
1. For example, Pylons is in maintenance mode, deform lacked a maintainer for a while, and pyramid_xmlrpc is no longer maintained in favor of pyramid_rpc. You can't get that information from an API, so a human must curate the projects. Further, pyramid_xmlrpc might be a project that we curate and eliminate from listing because of its status.

**Comment by stevepiercy** [comment]
1. [Check the boxes](https://github.com/Pylons/pylonsproject.org/issues/7#issue-124939859) and see what's left?
1. Deployment: @blaflamme can you reuse my public key from trypyramid.com? I have not tried yet.
1. Decide whether to flip the switch on DNS for www to point to the new site. Personally I think it's fine to move forward and switch DNS. If there's any straggling information out there, we can always carry it over from the pylonshq repo and submit new PRs to this repo.
1. Other items?

**Comment by zupo** [comment]
3. https://github.com/Pylons/pylonsproject.org/pull/21 needs to be merged and we need to add the /about-pylons-framework.html page, then I am +1 for flipping the DNS switch

**Comment by zupo** [comment]
1. Ah didn't realize I have the permissions to check them. Did not have it yesterday and did not re-check.

**Comment by zupo** [comment]
About curated projects: something like what we have on powered by pyramid page makes a ton of sense for me. A curated list with basic info, then for each one stats are pulled from github.

**Comment by blaflamme** [comment]
@stevepiercy yes you can deploy since it uses the same setup and info than for trypyramid.com

I don't think we want too much projects under the projects menu, and best would probably be to have a separate page for all projects instead of having a partial listing in the menu. And by `all projects` I mean active or `worth to be there` projects. There are too many repos under our Github account and not all of them belongs to the site.

**Comment by zupo** [comment]
This is what I meant: https://github.com/Pylons/trypyramid.com/blob/master/src/templates/community-powered-by-pyramid.json

Then each project can have ``display_in_nav`` and ``display_on_index`` to toggle displaying it in prominent positions. And all of them are displayed on /projects.html.

**Comment by zupo** [comment]
Connecting with GitHub API should probably be a different ticket though.

**Comment by blaflamme** [comment]
yes I got that and it's a good idea. However I'm not sure about having project in nav if we have that page and list main projects on the home page... Pyramid and Webob could be, probably, but still...

**Comment by zupo** [comment]
This is how I would do it:

Nav: Pyramid, WebOb, Waitress, All Projects
Front page: Up to 10 most important, plus link to Project page
Projects page: All project (that are in .json file)

**Comment by zupo** [comment]
Maybe have another flag ``deprecated``.

**Comment by blaflamme** [comment]
@zupo looks like a good plan

**Comment by blaflamme** [comment]
@zupo look at trypyramid to add support for the projects page

**Comment by stevepiercy** [comment]
I like `display_on_index` (I assume this would be the home page).

I'm unsure about `display_in_nav` due to potentially long list. I trust your judgment. We can always tweak it later.

Projects page sounds good.

**Comment by zupo** [comment]
OK, will start working on this.

**Comment by stevepiercy** [comment]
#21 is merged

**Comment by stevepiercy** [comment]
This was completed at DragonSprint
