### ISSUE TITLE
Documentation site is down (403)

### ISSUE THREAD

**Issue by equake** [Pylons/pylonsproject.org#75]
Hi, 
I'm having trouble reaching https://docs.pylonsproject.org/

```
403 Forbidden
cloudflare
```

Thanks.

**Comment by stevepiercy** [comment]
It's not a valid URL. You need to specify a project, for example:
https://docs.pylonsproject.org/projects/pyramid/en/latest/

**Comment by mmerickel** [comment]
Your valid URL is not working @stevepiercy .

**Comment by stevepiercy** [comment]
Meh, cache. Can't look into it for a couple hours.

**Comment by stevepiercy** [comment]
Duplicate of https://github.com/Pylons/pyramid/issues/3574
